### ISSUE TITLE
Use the JSON scripts instead the XML scripts for API requests

### ISSUE THREAD

**Issue by stefets** [MatejMecka/python-vlc-http#5]
Hi!

I like your lib and I would like to use it in my software as a plugin.

I have a fork because I need the playlist from the fetch_playlist. 

I would like to PR my changes but if this happen, the lib will call playlist.json and status.json instead of the xml scripts.

Are you OK to use the json script instead the xml script for the requests ?

**Comment by MatejMecka** [comment]
Hey there! I'm fine with that :D 

Thank you for wanting to contribute those changes :)

**Comment by stefets** [comment]
Hey @MatejMecka,

Thanks for the merge, will it be available on pypi.org eventually ?

**Comment by MatejMecka** [comment]
Hey there! I've published it on Pypi under 0.0.10. You can find the changes here: https://pypi.org/project/python-vlc-http/0.0.10/

I've also updated the main branch to reflect the changes :)

**Comment by stefets** [comment]
Hi @MatejMecka and thanks,

I have an issue to PIP install the package!

`$ pip install python-vlc-http==0.0.10
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: Could not find a version that satisfies the requirement python-vlc-http==0.0.10 (from versions: 0.0.10.macosx-12-arm64, 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9)
ERROR: No matching distribution found for python-vlc-http==0.0.10`

If I dont specify the 0.0.10 version, PIP install the version 0.0.9

I don't know why, I am on Linux,  do you have an idea ?

Meanwhile, I can use the 0.0.10 version in my environment.

**Comment by MatejMecka** [comment]
@stefets I think I resolved the issue!

I also released 0.0.11 to update the setup.py descriptions. I do not know what happened to ship a separate binary for mac, I thought that it'll automatically ship it for all platforms, but oh well haha. 

Let me know if it works!

**Comment by stefets** [comment]
Hi @MatejMecka,

It now works fine for me! Note that I am using Python 3.11 and it's all good!

`Installing collected packages: python-vlc-http`
`Successfully installed python-vlc-http-0.0.11`

I will complete the last VLC API implementation in a new PR in a couple of weeks and maybe some fixes or changes

Thanks!
